# Generated by Django 4.2.6 on 2023-12-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "actor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "genre",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("premiere_date", models.DateField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("seasons_count", models.IntegerField(blank=True, null=True)),
                ("episodes_count", models.IntegerField(blank=True, null=True)),
                (
                    "trailer_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("poster_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "production",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "review",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
        migrations.CreateModel(
            name="ActorProduction",
            fields=[
                (
                    "actor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="Website.actor",
                    ),
                ),
            ],
            options={
                "db_table": "actor_production",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FavoritesUserProduction",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="Website.user",
                    ),
                ),
            ],
            options={
                "db_table": "favorites_user_production",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ToWatch",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="Website.user",
                    ),
                ),
                ("priority", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "to_watch",
                "managed": False,
            },
        ),
    ]
