"""
Django settings for PIS project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import django
from django.utils.encoding import smart_str
import environ
import os
# Initialise environment variables
env = environ.Env()
environ.Env.read_env()
django.utils.encoding.smart_text = smart_str

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['20.229.152.181', '137.116.206.131', '10.1.1.4', '127.0.0.1']
CORS_ALLOW_ALL_ORIGINS = True

# Keycloak settings
KEYCLOAK_BEARER_AUTHENTICATION_EXEMPT_PATHS = [
    'admin', 'accounts',
    ]
CONFIG_DIR = os.path.join(os.path.dirname(__file__),os.pardir)
KEYCLOAK_CLIENT_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiRxmCgdVSTUb2AUoIkdWixbPFrl+eLFLO6pmn4jyKxPDBnf7X8uc3dlT1Ou5LhEh9LxvXB+RkgQqPf6xqPMLb7OvMKb06SSGV25PHGcRuKeoQR8oIr+zp/nK44jl9ombEqjLIe13WEMjeZ9E66OY643/OJIr3XEr8fh3dMrp6zqmDeZaMSfoPhNeLqqsw0YqvM+bn7MpyLut/ApM1E1w8Ipmc9vaIoS65Ya/EkoPmpAz7N5x/E5uzMN59SQ3UU0A3Bamyf3thmvHCDOIaTadaR1OroLUL1YNwQ8BmbsfcDTbt/udjJgQosgU1hh1C3Rt1AHqly37Vb7ousOatP5RSwIDAQAB
-----END PUBLIC KEY-----"""
KEYCLOAK_CONFIG = {
    'KEYCLOAK_REALM': 'PIS',
    'KEYCLOAK_CLIENT_ID': 'PIS-backend',
    'KEYCLOAK_DEFAULT_ACCESS': 'ALLOW',  # DENY or ALLOW
    'KEYCLOAK_AUTHORIZATION_CONFIG': os.path.join(CONFIG_DIR, 'authorization-config.json'),
    'KEYCLOAK_METHOD_VALIDATE_TOKEN': 'DECODE',
    'KEYCLOAK_SERVER_URL': 'https://keycloackpis.azurewebsites.net/auth/',
    'KEYCLOAK_CLIENT_SECRET_KEY': 'mlUG6DrNBXF6q4o5z98dwwoxy2CMCzms',
    'KEYCLOAK_CLIENT_PUBLIC_KEY': KEYCLOAK_CLIENT_PUBLIC_KEY,
}

# Application definition

INSTALLED_APPS = [
    'django_jenkins',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'Website',
    'storages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'Website.middleware.KeycloakMiddleware',
]

ROOT_URLCONF = 'PIS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PIS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env("DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWD"),
        'HOST': env("DB_HOST"),
        'PORT': env("DB_PORT"),
    }
}
JENKINS_TASKS = ( 
    "django_jenkins.tasks.run_pylint",
    "django_jenkins.tasks.run_pep8",
)

PYLINT_RCFILE = os.path.join(BASE_DIR, ".pylintrc")
PEP8_RCFILE = os.path.join(BASE_DIR, "setup.cfg")
PROJECT_APPS = ['Website']

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not env('DEV') == 'true':
    DEFAULT_FILE_STORAGE = 'PIS.custom_azure.AzureMediaStorage'
    STATICFILES_STORAGE = 'PIS.custom_azure.AzureStaticStorage'

    STATIC_LOCATION = "static"
    MEDIA_LOCATION = "media"

    AZURE_ACCOUNT_NAME = env('STORAGE_NAME')
    AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
    STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
    MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'
