/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dIRFWudE3dA
 */
"use client";
import React, { useEffect, useState } from 'react';
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function HomePage() {
  return (
    <div className="flex flex-col min-h-screen bg-gray-100">
      <header className="py-4 px-6 bg-white shadow">
        <div className="flex items-center justify-between">
          <Link href="#">
            <span className="text-xl font-bold text-black">Cinemania</span>
          </Link>
          <div className="flex items-center justify-end gap-4">
            <nav className="flex gap-4">
              <Link className="text-sm font-medium text-gray-700 hover:underline" href="#">
                Ranking
              </Link>
              <Link className="text-sm font-medium text-gray-700 hover:underline" href="#">
                Zarejestruj się
              </Link>
            </nav>
            <Link href="#">
              <UserIcon className="w-4 h-4 text-gray-500" />
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="relative w-full h-96">
          <img
            alt="Cinematic background"
            className="object-cover h-full w-full"
            height="768"
            src="https://wallpaperaccess.com/full/229832.jpg"
            style={{
              aspectRatio: "1366/768",
              objectFit: "cover",
            }}
            width="1366"
          />
          <div className="absolute top-0 left-0 w-full h-full bg-black/40 flex items-center justify-center">
            <div className="text-center">
              <h1 className="text-4xl font-bold text-white">Cinemania - wszystkie filmy w jednym miejscu</h1>
              <p className="text-lg text-white mt-2">Sprawdzaj i oceniaj swoje ulubione filmy</p>
              <div className="mt-4">
                <input className="w-64 py-2 px-4 rounded-md text-black" placeholder="Wyszukaj tytuł filmu" type="text" />
              </div>
            </div>
          </div>
        </section>
        <MovieCards />
      </main>
      <footer className="py-4 px-6 bg-white shadow-t">
        <div className="flex items-center justify-between">
          <p className="text-sm text-gray-500">© Cinemania. All rights reserved.</p>
          <nav className="flex gap-4">
            <Link className="text-sm text-gray-500 hover:underline" href="#">
              Privacy Policy
            </Link>
            <Link className="text-sm text-gray-500 hover:underline" href="#">
              Terms of Service
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function Movie({title, description}) {
  return (
    // <div>
    <Card>
      <CardHeader>
        <h3 className="text-lg font-bold text-black">{title}</h3>
        <Badge className="text-black">8.4</Badge>
      </CardHeader>
      <CardContent>
        <img
          alt="Movie poster"
          className="w-full h-64 object-cover"
          height="200"
          src="https://th.bing.com/th/id/OIP.VoUvM9GU4u_ZQIEU5629TgHaK-?rs=1&pid=ImgDetMain"
          style={{
            aspectRatio: "200/200",
            objectFit: "cover",
          }}
          width="200" />
        <p className="mt-4 text-black">{description}</p>
      </CardContent>
    </Card>
  // </div>
  )
}

function MovieCards() {
  const [userName, setUserName] = useState('');

  useEffect(() => {
    const fetchUser = async () => {
      try {
        const response = await fetch('http://137.116.206.131/productions/6');
        // , 
        // {
        //   headers: {
        //     Accept: 'application/json'
        //   }
        // });
        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }
        const data = await response.json();
        setUserName(data.title);
      } catch (error) {
        console.error('Error fetching joke:', error);
      }
    };
    fetchUser();
  }, []);
  
  return (
    <section className="px-6 py-12">
      <h2 className="text-2xl font-bold text-black mb-6">Trending Movies</h2>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
        <Movie title={userName} description="This is a placeholder movie description" />
        {/* Możesz dodać więcej komponentów Movie z innymi żartami lub opisami */}
      </div>
    </section>
  );
}



function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
